# See for details:
#   http://docs.python.org/3.2/library/logging.config.html#dictionary-schema-details

disable_existing_loggers: false
formatters:
    standard:
        format: "%(asctime)s [%(levelname)s] %(name)s: %(message)s"
handlers:
    console:
        level: INFO
        class: logging.StreamHandler
        formatter: standard
root:
    level: DEBUG
    handlers:
        - console

loggers:
    kazoo:
        level: WARNING
