# See for details:
#   http://docs.python.org/3.2/library/logging.config.html#dictionary-schema-details

version: 1

disable_existing_loggers: false

formatters:
    console:
        (): contextlog.make_mixed_formatter
        formatters:
            - colorlog.ColoredFormatter
            - contextlog.PartialFormatter
            - contextlog.ExceptionLocalsFormatter
        style: "{"
        format: "{asctime} {fg_bold_blue}{app:9.9} {purple}{name:35.35} {log_color}{levelname:>7} {yellow}{job_id:36.36}{reset} {message} -- {cyan}{_extra}{reset}"
    file:
        (): contextlog.make_mixed_formatter
        formatters:
            - contextlog.PartialFormatter
            - contextlog.ExceptionLocalsFormatter
        style: "{"
        format: "{asctime} {app:9.9} {name:35.35} {levelname:>7} {job_id:36.36} {message} -- {_extra}"
    json:
        (): jsonformatter.JsonFormatter
        json_depth: 2


handlers:
    console:
        level: WARN
        class: logging.StreamHandler
        formatter: console
    file:
        level: INFO
        class: logging.FileHandler
        filename: /var/log/powny/powny.log
        formatter: file
    debug_file:
        level: DEBUG
        class: logging.FileHandler
        filename: /var/log/powny/powny.debug.log
        formatter: file
    json_file:
        level: INFO
        class: logging.FileHandler
        filename: /var/log/powny/powny.json.log
        formatter: json

root:
    level: DEBUG
    handlers:
        - console
        - file
        - debug_file
        - json_file

loggers:
    kazoo:
        level: WARNING
    elasticsearch:
        level: WARNING
