# See for details:
#   http://docs.python.org/3.2/library/logging.config.html#dictionary-schema-details

disable_existing_loggers: false
formatters:
    console:
        (): contextlog.make_mixed_formatter
        formatters:
            - contextlog.PartialFormatter
            - contextlog.ExceptionLocalsFormatter
        style: "{"
        format: "{yellow}{asctime} {log_color}{levelname:>7} {purple}{name:20.20}{reset} {message} {_extra}"
    file:
        (): contextlog.make_mixed_formatter
        formatters:
            - contextlog.PartialFormatter
            - contextlog.ExceptionLocalsFormatter
        style: "{"
        format: "{asctime} {levelname:>7} {name:20.20} {message} {_extra}"
handlers:
    console:
        level: WARN
        class: logging.StreamHandler
        formatter: console
    file:
        level: INFO
        class: logging.handlers.RotatingFileHandler
        filename: /var/log/powny/powny.log
        formatter: file
root:
    level: DEBUG
    handlers:
        - console
        - file

loggers:
    kazoo:
        level: WARNING
