# See for details:
#   http://docs.python.org/3.2/library/logging.config.html#dictionary-schema-details

disable_existing_loggers: false
formatters:
    standard:
        (): contextlog.make_mixed_formatter
        formatters:
            - contextlog.PartialFormatter
            - contextlog.ExceptionLocalsFormatter
        style: "{"
        format: "{yellow}{asctime} {log_color}{levelname:>7} {purple}{name:20.20}{reset} {message}"
handlers:
    console:
        level: INFO
        class: logging.StreamHandler
        formatter: standard
root:
    level: DEBUG
    handlers:
        - console

loggers:
    kazoo:
        level: WARNING
